fastlane_version "2.63.0"

default_platform :android

platform :android do
  ENV["FASTLANE_HIDE_CHANGELOG"] = "true"  
  ENV["FASTLANE_SKIP_UPDATE_CHECK"] = "true"    

  PROJECT_NAME = "comics-app-android"   

  # public lanes
  desc "build"
  lane :build_debug do |options|
    gradle(
      task: "clean",
    )
    build_android_app(
      task: 'assemble',
      build_type: 'Debug'
    )
    build_android_app(
      task: 'assemble',
      build_type: 'AndroidTest'
    )

    OUTPUT_DIRECTORY_DEFAULT = "../build/apk/"
    initial_apk_path = File.absolute_path(Dir.glob("../**/*.apk").last)
    date_time = Time.now.strftime("%Y%m%d%H%M")
    apk_filename = PROJECT_NAME+"-"+date_time+ ".apk"
    final_apk_path = OUTPUT_DIRECTORY_DEFAULT+apk_filename
    sh 'mkdir ../build'
    sh 'mkdir ../build/apk'
    sh 'cp '+initial_apk_path+' '+final_apk_path

    screengrab(
     locales: ['en-US'],
     clear_previous_screenshots: true,
     test_instrumentation_runner: "android.support.test.runner.AndroidJUnitRunner",
     tests_apk_path: 'app/build/outputs/apk/debug/app-debug.apk'
    )
  end
  desc "Build debug and test APK for screenshots"
  lane :build_for_screengrab do
   gradle(task: "assembleDebug assembleAndroidTest")
   screengrab(
     locales: ['en-US'],
     clear_previous_screenshots: true,
     test_instrumentation_runner: "android.support.test.runner.AndroidJUnitRunner",
     tests_apk_path: 'app/build/outputs/apk/debug/app-debug.apk'
   )
  end

end